
# Config for functions/<name>/config.toml
# Read more about customization here: https://supabase.com/docs/guides/functions/configuration

[build]
language = "deno"

[deploy]
run-commands = ["deno cache index.ts"]
